name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:    
    branches: [main]

jobs:

  deploy:
    # Our previously created self-hosted runner
    runs-on: self-hosted

    # A sequence of tasks that will execute as part of the job
    steps:
      # Checks out repository so our job can access it
      - uses: actions/checkout@v3
      # We will output publish files to the folder we previously created
      - name: Install dependencies
        run: yarn
        
      - name: Build
        run: yarn run build
        
      - name: Restart host service
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart hyplix_discord_bot.service

